In [3]:
import numpy as np

# multi dmension array

A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

print(A.ndim)
print(A.shape)

2
(3, 2)


In [8]:
# matrix multiplication(dot product)

A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
B = np.array([
    [10, 20],
    [30, 40]
])

result = np.dot(A, B)

print(f"{A.shape} * {B.shape} -> {result.shape}")
print(result)

(3, 2) * (2, 2) -> (3, 2)
[[ 70 100]
 [150 220]
 [230 340]]


In [ ]:
# matrix multiplication(dot product) 
#  -ERROR: A's second dimension must be same as B's first dimension

A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
B = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])

result = np.dot(A, B)

print(f"{A.shape} * {B.shape} -> {result.shape}")
print(result)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

# Neural Network

<img src="imgs/single_layer_neural_network.png" width="400">

this neural network can be implemented like next matrix equation

$$
\begin{bmatrix}
x_1& x_2
\end{bmatrix}
\cdot
\begin{bmatrix}
1& 3& 5 \\
2& 4& 6
\end{bmatrix}
=
\begin{bmatrix}
y_1& y_2& y_3
\end{bmatrix}
$$


In [1]:
# single layer Neural Network

import numpy as np


X = np.array([11, 22])
W = np.array([
    [1, 3, 5],
    [2, 4, 6]
])

Y = np.dot(X, W)

print(f"{X}\n*\n{W}\n= {Y}")

[11 22]
*
[[1 3 5]
 [2 4 6]]
= [ 55 121 187]


In [45]:
# Three layer Neural Network with bias

import numpy as np

# layer1
X = np.array([1.0, 0.5])
W2_1 = np.array([
    [0.5, 1.1, 0.4],
    [2.0, 0.8, 2.2]
])
b1 = 0.1
L1 = np.dot(X, W2_1) + b1
print(L1)

# layer2
W3_2 = np.array([
    [0.1, 0.0],
    [0.2, 0.1],
    [0.0, 0.6]
]) 
b2 = 0.5
L2 = np.dot(L1, W3_2) + b2
print(L2)

# layer3(output)
W4_3 = np.array([
    [0.4, 0.3],
    [0.5, 0.5]
])
b3 = -1.2
L3 = np.dot(L2, W4_3) + b3
print(L3)

print(f"input: {X.shape} W2_1: {W2_1.shape} W3_2: {W3_2.shape} W4_3: {W4_3.shape} output: {L3.shape}")

[1.6 1.6 1.6]
[0.98 1.62]
[ 0.002 -0.096]
input: (2,) W2_1: (2, 3) W3_2: (3, 2) W4_3: (2, 2) output: (2,)


In [46]:
# Three layer Neural Network with bias and active function

import numpy as np

def sigmoid(X):
    return 1 / (1 + np.exp(-X))

# layer1
X = np.array([1.0, 0.5])
W2_1 = np.array([
    [0.5, 1.1, 0.4],
    [2.0, 0.8, 2.2]
])
b1 = 0.1
A1 = np.dot(X, W2_1) + b1
L1 = sigmoid(A1)
print(L1)

# layer2
W3_2 = np.array([
    [0.1, 0.0],
    [0.2, 0.1],
    [0.0, 0.6]
]) 
b2 = 0.5
A2 = np.dot(L1, W3_2) + b2
L2 = sigmoid(A2)
print(L2)

# layer3(output)
W4_3 = np.array([
    [0.4, 0.3],
    [0.5, 0.5]
])
b3 = -1.2
A3 = np.dot(L2, W4_3) + b3
L3 = sigmoid(A3)
print(L3)

print(f"input: {X.shape} W2_1: {W2_1.shape} W3_2: {W3_2.shape} W4_3: {W4_3.shape} output: {L3.shape}")

[0.83201839 0.83201839 0.83201839]
[0.67909274 0.74695032]
[0.36473116 0.34914558]
input: (2,) W2_1: (2, 3) W3_2: (3, 2) W4_3: (2, 2) output: (2,)


In [47]:
# Three layer Neural Network with bias, active function, output active function

import numpy as np

def sigmoid(X):
    return 1 / (1 + np.exp(-X))

def identity_function(X):
    return X

# layer1
X = np.array([1.0, 0.5])
W2_1 = np.array([
    [0.5, 1.1, 0.4],
    [2.0, 0.8, 2.2]
])
b1 = 0.1
A1 = np.dot(X, W2_1) + b1
L1 = sigmoid(A1)
print(L1)

# layer2
W3_2 = np.array([
    [0.1, 0.0],
    [0.2, 0.1],
    [0.0, 0.6]
]) 
b2 = 0.5
A2 = np.dot(L1, W3_2) + b2
L2 = sigmoid(A2)
print(L2)

# layer3(output)
W4_3 = np.array([
    [0.4, 0.3],
    [0.5, 0.5]
])
b3 = -1.2
A3 = np.dot(L2, W4_3) + b3
L3 = identity_function(A3)
print(L3)

print(f"input: {X.shape} W2_1: {W2_1.shape} W3_2: {W3_2.shape} W4_3: {W4_3.shape} output: {L3.shape}")

[0.83201839 0.83201839 0.83201839]
[0.67909274 0.74695032]
[-0.55488774 -0.62279702]
input: (2,) W2_1: (2, 3) W3_2: (3, 2) W4_3: (2, 2) output: (2,)


In [48]:
# Neural Network Fucntion Refectoring

def sigmoid(X):
    return 1 / (1 + np.exp(-X))

def identity_function(X):
    return X

def init_network():
    network = {}
    network['W1'] = np.array([[0.5, 1.1, 0.4], [2.0, 0.8, 2.2]])
    network['b1'] = np.array([0.1, 0.1, 0.1])
    network['W2'] = np.array([[0.1, 0.0], [0.2, 0.1], [0.0, 0.6]])
    network['b2'] = np.array([0.5, 0.5])
    network['W3'] = np.array([[0.4, 0.3], [0.5, 0.5]])
    network['b3'] = np.array([-1.2, -1.2])

    return network

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    L1 = sigmoid(np.dot(x, W1) + b1)
    L2 = sigmoid(np.dot(L1, W2) + b2)
    L3 = identity_function(np.dot(L2, W3) + b3)

    return L3

network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)
print(y)

[-0.55488774 -0.62279702]


# Output Layer

In [10]:
# simple softmax function

import numpy as np

a = np.array([2, 4, 10])

exp_a = np.exp(a)

softmax_result = a / np.sum(exp_a)

print(softmax_result)

[9.05450463e-05 1.81090093e-04 4.52725232e-04]


In [11]:
# simple softmax function - flaw: overflow

import numpy as np

a = np.array([1010, 1000, 990])

exp_a = np.exp(a)

softmax_result = a / np.sum(exp_a)

print(softmax_result)

[0. 0. 0.]


/tmp/ipykernel_11433/3036156470.py:7: RuntimeWarning: overflow encountered in exp
  exp_a = np.exp(a)


## How to prevent Oerflow

We can transform softmax function($y_k$) like below
$$
\begin{aligned}
y_k &= \frac{\exp{a_k}}{\sum_{i=1}^{n}\exp{a_i}} = \frac{C\exp{a_k}}{C\sum_{i=1}^{n}\exp{a_i}} = \frac{\exp{\left(a_k+\log{C}\right)}}{\sum_{i=1}^{n}\exp{\left(a_i+\log{C}\right)}} \\
    &= \frac{\exp{\left(a_k+C'\right)}}{\sum_{i=1}^{n}\exp{\left(a_i+C'\right)}}
\end{aligned}
$$

commonly people set $C'$ to minus of the max value


In [12]:
# optimized softmax function

import numpy as np

def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    return exp_a / sum_exp_a

a = np.array([1010, 1000, 990])
result = softmax(a)

print(result)

[9.99954600e-01 4.53978686e-05 2.06106005e-09]


## Feature of Softmax Function

- The value lies between 0 and 1
- The value sum to 1
- The function is monotonically increasing.

Because of this features, the Softmax function is used to represent probabilities. And The relative size of the input values are preserved in the output. Therefore, the Softmax function is not used for output function when computational resources need to be conserved.